spring.application.name=SuiviPlus
server.port=8080

jwt.secret=MY_SUPER_SECRET_KEY_12345678901234567890
jwt.expiration=86400000

spring.datasource.url=jdbc:postgresql://localhost:5432/suiviplus
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
